name: Github Pages

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          lfs: 'true'

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          GCP_API_KEY: ${{ secrets.GCP_API_KEY }}
          GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}

      - name: Generate
        run: npm run generate
        env:
          GCP_API_KEY: ${{ secrets.GCP_API_KEY }}
          GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
